/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI;

import hotelGUI.clientGUI.AmenityPanel;
import hotelGUI.clientGUI.MaintenancePanel;
import hotelGUI.clientGUI.TransportPanel;
import hotelGUI.clientGUI.WakePanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Jermaine
 */
public class ClientPage extends javax.swing.JFrame {
    
    GridBagLayout layout = new GridBagLayout();
    final MaintenancePanel MaintenanceView; 
    final TransportPanel  transportView;
    final WakePanel  wakeView;
    final AmenityPanel  amenityView;

    /**
     * Creates new form mainMenuPage
     */
    public ClientPage() {
        initComponents();
        MaintenanceView =  new MaintenancePanel();
        transportView = new TransportPanel();
        wakeView = new WakePanel();
        amenityView = new AmenityPanel();
        contentPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(transportView,c);
        transportView.setVisible(false);
        
        //c.gridx = 0; c.gridy = 0;        
        contentPanel.add(MaintenanceView,c);
        MaintenanceView.setVisible(false);
        
        //c.gridx = 0; c.gridy = 0;        
        contentPanel.add(wakeView,c);
        wakeView.setVisible(false);
        
        contentPanel.add(amenityView,c);
        amenityView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        tourButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        TransportButton = new javax.swing.JButton();
        wakeButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        amenitiesButton = new javax.swing.JButton();
        eventButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        hoteName = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        contentPanel.setBackground(new java.awt.Color(204, 204, 255));

        tourButton.setText("Tours");
        tourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourButtonActionPerformed(evt);
            }
        });

        orderButton.setText("Order Food");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        TransportButton.setText("Transportation Services");
        TransportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransportButtonActionPerformed(evt);
            }
        });

        wakeButton.setText("Arrange A Wake Up Call");
        wakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wakeButtonActionPerformed(evt);
            }
        });

        maintenanceButton.setText("Call Maintenance");
        maintenanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceButtonActionPerformed(evt);
            }
        });

        amenitiesButton.setText("Amenities / Requests");
        amenitiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amenitiesButtonActionPerformed(evt);
            }
        });

        eventButton.setText("Events");
        eventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amenitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(orderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TransportButton)
                .addGap(18, 18, 18)
                .addComponent(wakeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maintenanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amenitiesButton)
                .addGap(18, 18, 18)
                .addComponent(eventButton)
                .addGap(18, 18, 18)
                .addComponent(tourButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        hoteName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hoteName.setText("AllSuites Hotel");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(hoteName)
                .addGap(76, 76, 76)
                .addComponent(logoutButton)
                .addContainerGap())
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(hoteName))
                .addGap(43, 43, 43)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(526, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButtonActionPerformed
        new eventsPage().setVisible(true);  
        menuPanel.setVisible(false);
        amenityView.setVisible(false);
        MaintenanceView.setVisible(false);
        wakeView.setVisible(false);
        transportView.setVisible(false);
    }//GEN-LAST:event_eventButtonActionPerformed

    private void amenitiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amenitiesButtonActionPerformed
        amenityView.setVisible(true); 
        menuPanel.setVisible(false);
        MaintenanceView.setVisible(false);
        transportView.setVisible(false);
        wakeView.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_amenitiesButtonActionPerformed

    private void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceButtonActionPerformed
        MaintenanceView.setVisible(true); 
        menuPanel.setVisible(false);
        transportView.setVisible(false);
        amenityView.setVisible(false);
        wakeView.setVisible(false);
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    private void wakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wakeButtonActionPerformed
        wakeView.setVisible(true);
        menuPanel.setVisible(false);
        MaintenanceView.setVisible(false);
        transportView.setVisible(false);
        menuPanel.setVisible(false);
        amenityView.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_wakeButtonActionPerformed

    private void TransportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransportButtonActionPerformed
        transportView.setVisible(true);
        menuPanel.setVisible(false);
        MaintenanceView.setVisible(false);
        amenityView.setVisible(false);
        wakeView.setVisible(false);
    }//GEN-LAST:event_TransportButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        new foodOrderPage().setVisible(true); 
        menuPanel.setVisible(false);
        transportView.setVisible(false);
        MaintenanceView.setVisible(false);
        amenityView.setVisible(false);
        wakeView.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_orderButtonActionPerformed

    private void tourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourButtonActionPerformed
        new toursPage().setVisible(true);  
        menuPanel.setVisible(false);
        MaintenanceView.setVisible(false);
        transportView.setVisible(false);
        amenityView.setVisible(false);
        wakeView.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_tourButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new welcomePage().setVisible(true);  
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransportButton;
    private javax.swing.JButton amenitiesButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton eventButton;
    private javax.swing.JLabel hoteName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton maintenanceButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton tourButton;
    private javax.swing.JButton wakeButton;
    // End of variables declaration//GEN-END:variables
}
