/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI;

import HSMmodel.employee;
import hotelGUI.employeeGUI.ClockPanel;
import hotelGUI.employeeGUI.HoursPanel;
import hotelGUI.employeeGUI.ProfilePanel;
import hotelGUI.receptionGUI.AmenityPanel;
import hotelGUI.receptionGUI.EventPanel;
import hotelGUI.receptionGUI.RoomPanel;
import hotelGUI.receptionGUI.TransportPanel;
import hotelGUI.receptionGUI.WakePanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Noria Soumbou
 */
public class ReceptionistPage extends javax.swing.JFrame {
    public static employee emp = new employee();
    GridBagLayout layout = new GridBagLayout();
    RoomPanel roomView;
    ClockPanel clockView; 
    ProfilePanel  profileView;
    HoursPanel  hoursView;
    WakePanel wakeView;
    TransportPanel transView;
    AmenityPanel AmenityView;
    EventPanel eventView;
    
    

    ReceptionistPage(String text) {
         initComponents();
         emp.setemail(text);
         emp.getEmployeeByEmail();
         this.setTitle(" Hello "+ emp.getfullname());
         init_panel();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void init_panel(){
        roomView =  new RoomPanel();
        clockView =  new ClockPanel(emp.getid());
        profileView = new ProfilePanel();
        hoursView = new HoursPanel(emp.getid());
        wakeView = new WakePanel();
        transView = new TransportPanel();
        AmenityView = new AmenityPanel();
        eventView = new EventPanel();
        contentPanel.setLayout(layout);
        
        
        contentPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(roomView,c);
        roomView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add( eventView,c);
        eventView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(AmenityView,c);
        AmenityView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(transView,c);
        transView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(profileView,c);
        profileView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(clockView,c);
        clockView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(hoursView,c);
        hoursView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add( wakeView,c);
        wakeView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        roommenu = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        wakemenu = new javax.swing.JMenuItem();
        transmenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        clockMenu = new javax.swing.JMenuItem();
        hoursMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        amenitymenu = new javax.swing.JMenuItem();
        eventmenu = new javax.swing.JMenuItem();
        tourmenu = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Rooms ");

        roommenu.setText("Rooms");
        roommenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roommenuActionPerformed(evt);
            }
        });
        jMenu1.add(roommenu);

        jMenuItem6.setText("Reservation");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clients");

        wakemenu.setText("Wake-up");
        wakemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wakemenuActionPerformed(evt);
            }
        });
        jMenu2.add(wakemenu);

        transmenu.setText("Transportation");
        transmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmenuActionPerformed(evt);
            }
        });
        jMenu2.add(transmenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("User");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        clockMenu.setText("Clock in or out");
        clockMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockMenuActionPerformed(evt);
            }
        });
        jMenu3.add(clockMenu);

        hoursMenu.setText("Hours");
        hoursMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursMenuActionPerformed(evt);
            }
        });
        jMenu3.add(hoursMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Activities");

        amenitymenu.setText("Amenities");
        amenitymenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amenitymenuActionPerformed(evt);
            }
        });
        jMenu4.add(amenitymenu);

        eventmenu.setText("Events");
        eventmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventmenuActionPerformed(evt);
            }
        });
        jMenu4.add(eventmenu);

        tourmenu.setText("Tours");
        jMenu4.add(tourmenu);

        jMenuBar1.add(jMenu4);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clockMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockMenuActionPerformed
        clockView.setVisible(true);
        hoursView.setVisible(false);
        roomView.setVisible(false);
        wakeView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
         eventView.setVisible(false);
    }//GEN-LAST:event_clockMenuActionPerformed

    private void roomMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomMenuActionPerformed
        clockView.setVisible(false);
        hoursView.setVisible(false);
        roomView.setVisible(true);
        wakeView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
         eventView.setVisible(false);
    }//GEN-LAST:event_roomMenuActionPerformed

    private void reservationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationMenuActionPerformed
        roomView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        wakeView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
         eventView.setVisible(false);
    }//GEN-LAST:event_reservationMenuActionPerformed

    private void wakeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wakeMenuActionPerformed
        wakeView.setVisible(true);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        roomView.setVisible(false);
        transView.setVisible(false);
        eventView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_wakeMenuActionPerformed

    private void transportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportMenuActionPerformed
        transView.setVisible(true);
        roomView.setVisible(false);
        wakeView.setVisible(false);
        eventView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_transportMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        roomView.setVisible(false);
        wakeView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        roomView.setVisible(false);
        wakeView.setVisible(false);
        clockView.setVisible(false);
        eventView.setVisible(false);
        hoursView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        roomView.setVisible(false);
        wakeView.setVisible(false);
        eventView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        roomView.setVisible(false);
        wakeView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        eventView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void hoursMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursMenuActionPerformed
        hoursView.setVisible(true);
        roomView.setVisible(false);
        wakeView.setVisible(false);
        eventView.setVisible(false);
        clockView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
    }//GEN-LAST:event_hoursMenuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        new welcomePage().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void amenitymenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amenitymenuActionPerformed
         AmenityView.setVisible(true);
         hoursView.setVisible(false);
        roomView.setVisible(false);
        wakeView.setVisible(false);
        eventView.setVisible(false);
        clockView.setVisible(false);
        transView.setVisible(false);
    }//GEN-LAST:event_amenitymenuActionPerformed

    private void wakemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wakemenuActionPerformed
        wakeView.setVisible(true);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        roomView.setVisible(false);
        eventView.setVisible(false);
        transView.setVisible(false);
        AmenityView.setVisible(false);
    }//GEN-LAST:event_wakemenuActionPerformed

    private void eventmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventmenuActionPerformed
        eventView.setVisible(true);
        wakeView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        roomView.setVisible(false);
        transView.setVisible(false);
        AmenityView.setVisible(false);
    }//GEN-LAST:event_eventmenuActionPerformed

    private void transmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmenuActionPerformed
        transView.setVisible(true);
        eventView.setVisible(false);
        wakeView.setVisible(false);
        clockView.setVisible(false);
        hoursView.setVisible(false);
        roomView.setVisible(false);        
        AmenityView.setVisible(false);
    }//GEN-LAST:event_transmenuActionPerformed

    private void roommenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roommenuActionPerformed
        clockView.setVisible(false);
        hoursView.setVisible(false);
        roomView.setVisible(true);
        wakeView.setVisible(false);
        transView.setVisible(false);
         AmenityView.setVisible(false);
         eventView.setVisible(false);
    }//GEN-LAST:event_roommenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReceptionistPage("").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem amenitymenu;
    private javax.swing.JMenuItem clockMenu;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuItem eventmenu;
    private javax.swing.JMenuItem hoursMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem roommenu;
    private javax.swing.JMenuItem tourmenu;
    private javax.swing.JMenuItem transmenu;
    private javax.swing.JMenuItem wakemenu;
    // End of variables declaration//GEN-END:variables
}
