/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI;

import HSMmodel.employee;
import hotelGUI.employeeGUI.ClockPanel;
import hotelGUI.employeeGUI.HoursPanel;
import hotelGUI.employeeGUI.ProfilePanel;
import hotelGUI.receptionGUI.RoomPanel;
import hotelGUI.receptionGUI.WakePanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Noria Soumbou
 */
public class ReceptionistPage extends javax.swing.JFrame {
    public static employee emp = new employee();
    GridBagLayout layout = new GridBagLayout();
    RoomPanel roomView;
    ClockPanel clockView; 
    ProfilePanel  profileView;
    HoursPanel  hoursView;
    WakePanel wakeView;
    
    
    

    ReceptionistPage(String text) {
         initComponents();
         emp.setemail(text);
         emp.getEmployeeByEmail();
         init_panel();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void init_panel(){
        roomView =  new RoomPanel();
        clockView =  new ClockPanel(emp.getid());
        profileView = new ProfilePanel();
        hoursView = new HoursPanel();
        wakeView = new WakePanel();
        contentPanel.setLayout(layout);
        
        contentPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(roomView,c);
        roomView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(profileView,c);
        profileView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(clockView,c);
        clockView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(hoursView,c);
        hoursView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add( wakeView,c);
        wakeView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        roomMenu = new javax.swing.JMenuItem();
        reservationMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        wakeMenu = new javax.swing.JMenuItem();
        transportMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        clockMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Rooms ");

        roomMenu.setText("Rooms");
        roomMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomMenuActionPerformed(evt);
            }
        });
        jMenu1.add(roomMenu);

        reservationMenu.setText("Reservation");
        reservationMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationMenuActionPerformed(evt);
            }
        });
        jMenu1.add(reservationMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clients");

        wakeMenu.setText("Wake-up");
        wakeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wakeMenuActionPerformed(evt);
            }
        });
        jMenu2.add(wakeMenu);

        transportMenu.setText("Transportation");
        transportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportMenuActionPerformed(evt);
            }
        });
        jMenu2.add(transportMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("User");

        clockMenu.setText("Clock in or out");
        clockMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockMenuActionPerformed(evt);
            }
        });
        jMenu3.add(clockMenu);

        jMenuItem2.setText("Hours");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Activities");

        jMenuItem3.setText("Amenities");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Events");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Tours");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clockMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockMenuActionPerformed
         roomView.setVisible(false);
         wakeView.setVisible(false);
    }//GEN-LAST:event_clockMenuActionPerformed

    private void roomMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomMenuActionPerformed
         roomView.setVisible(true);
         wakeView.setVisible(false);
    }//GEN-LAST:event_roomMenuActionPerformed

    private void reservationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationMenuActionPerformed
        roomView.setVisible(false);
    }//GEN-LAST:event_reservationMenuActionPerformed

    private void wakeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wakeMenuActionPerformed
        wakeView.setVisible(true);
        roomView.setVisible(false);
    }//GEN-LAST:event_wakeMenuActionPerformed

    private void transportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportMenuActionPerformed
        roomView.setVisible(false);
        wakeView.setVisible(false);
    }//GEN-LAST:event_transportMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         roomView.setVisible(false);
         wakeView.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         roomView.setVisible(false);
         wakeView.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         roomView.setVisible(false);
         wakeView.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         roomView.setVisible(false);
         wakeView.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistPage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clockMenu;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem reservationMenu;
    private javax.swing.JMenuItem roomMenu;
    private javax.swing.JMenuItem transportMenu;
    private javax.swing.JMenuItem wakeMenu;
    // End of variables declaration//GEN-END:variables
}
