/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.managerGUI;
import dbConnexion.SQLiteJDBConnection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noria Soumbou
 */
public class allRoomPanel extends javax.swing.JPanel {

    final private SQLiteJDBConnection db = new SQLiteJDBConnection();
        
    /**
     * Creates new form allRoomPanel
     */
    public allRoomPanel() {
        initComponents();
        fillTable();
    }
    
    private void fillTable(){
     DefaultTableModel model = (DefaultTableModel) roomTable.getModel();
     model.addRow(new Object[]{"Room 1", "Column 2", "Column 3", 4});
      
     /* String[] column = new String [] {"id", "room", "location", "ltype", "bed", "price", "status", "null"};
       Object [][] data = new Object [][] {
                { 1, "wow", "w", "w",  new Integer(3),  new Double(3.0), "w", "w"},
                { 2, "wreck", "wr", "wr",  new Integer(3),  new Double(3.0), "wr", "wr"},
                { 3, "fries", "f", "f",  new Integer(3),  new Double(3.0), "f", "f"}
            };
        //roomTable.setValueAt("test", 2, 2);
        DefaultTableModel tmodel = new DefaultTableModel(data,column);
        roomTable.setModel(tmodel);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        roomTable.setPreferredSize(new java.awt.Dimension(300, 64));
        jScrollPane1.setViewportView(roomTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roomTable;
    // End of variables declaration//GEN-END:variables


}
