/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.managerGUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Noria Soumbou
 */
public class RoomPanel extends javax.swing.JPanel {
    GridBagLayout layout = new GridBagLayout();
    final AddRoomPanel addView; 
    final allRoomPanel  roomView;
    final occupiedRoomPanel  occupiedView;
    final freeRoomPanel freeView;
    
    /**
     * Creates new form RoomPanel
     */
    public RoomPanel() {
        initComponents();
        addView =  new AddRoomPanel();
        roomView = new allRoomPanel();
        occupiedView = new  occupiedRoomPanel();
        freeView = new freeRoomPanel();
        content.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0; c.gridy = 0;        
        content.add(roomView,c);
        roomView.setVisible(true);
        allButton.setSelected(true);
        
        c.gridx = 0; c.gridy = 0;        
        content.add(addView,c);
        addView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        content.add(occupiedView,c);
        occupiedView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        content.add(freeView,c);
        freeView.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        allButton = new javax.swing.JButton();
        occupiedButton = new javax.swing.JButton();
        freeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(255, 255, 255));
        sideBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        allButton.setText("view all");
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });

        occupiedButton.setText("Occupied");
        occupiedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupiedButtonActionPerformed(evt);
            }
        });

        freeButton.setText("Free");
        freeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(occupiedButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(freeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(allButton)
                .addGap(18, 18, 18)
                .addComponent(occupiedButton)
                .addGap(18, 18, 18)
                .addComponent(freeButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        content.setPreferredSize(addView.getSize());
        roomView.setVisible(false);        
        addView.setVisible(true);        
        occupiedView.setVisible(false);      
        freeView.setVisible(false);
        content.validate();
    }//GEN-LAST:event_addButtonActionPerformed

    private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allButtonActionPerformed
        content.setPreferredSize(roomView.getSize());
        roomView.setVisible(true);        
        addView.setVisible(false);        
        occupiedView.setVisible(false);      
        freeView.setVisible(false);
        //content.revalidate();
        this.validate();
    }//GEN-LAST:event_allButtonActionPerformed

    private void occupiedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupiedButtonActionPerformed
        content.setPreferredSize(occupiedView.getSize());
        roomView.setVisible(false);        
        addView.setVisible(false);        
        occupiedView.setVisible(true);      
        freeView.setVisible(false);
        this.validate();
    }//GEN-LAST:event_occupiedButtonActionPerformed

    private void freeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeButtonActionPerformed
        content.setPreferredSize(freeView.getSize());
        roomView.setVisible(false);        
        addView.setVisible(false);        
        occupiedView.setVisible(false);      
        freeView.setVisible(true);
        content.validate();
    }//GEN-LAST:event_freeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton allButton;
    private javax.swing.JPanel content;
    private javax.swing.JButton freeButton;
    private javax.swing.JButton occupiedButton;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
