/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.receptionGUI;

import hotelGUI.clientGUI.*;
import dbConnexion.SQLiteJDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noria Soumbou
 */
public class EventPanel extends javax.swing.JPanel {
    
    final private SQLiteJDBConnection db = new SQLiteJDBConnection();
    
    /**
     * Creates new form EventPanel
     */
    public EventPanel() {
        initComponents();
        fillTable();
    }
    
    private void fillTable(){
        DefaultTableModel model = (DefaultTableModel) eventTable.getModel();

        String sql = "SELECT * FROM event";
        try (Connection conn = db.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            try (ResultSet rs = pstmt.executeQuery()) {
                if(rs.next()) {
                    //TODO change to date
                  model.addRow(new Object[]{ rs.getInt("idEvent"), rs.getString("title"), rs.getString("description"), 
                      rs.getString("date"),rs.getString("timeBegin"),rs.getString("timeEnd"),rs.getInt("fee")});
                  System.out.println("event: "+ rs.getString("title"));
                }
                rs.close();
            }catch(SQLException e){ System.out.println("all event: "+e.getMessage()); }            
            pstmt.close();
            //conn.close();
        } catch (SQLException e) {
            System.out.println("all event db"+e.getMessage());
        }
        //System.out.println(eventTable.getValueAt(1, 1));
        eventTable.removeColumn(eventTable.getColumnModel().getColumn(0)); // hide id
        eventTable.setDefaultEditor(Object.class, null);
    }
    
    /**
     * Update the invoice of the client
     * @param id client id
     * @param fee 
     */
    private void updateInvoice( int id, int fee){
        // TODO WRITE CODE
    }
    
    private boolean isRegister( int idc, int ide){
        // TODO WRITE CODE
        return false;
    }
    
    private void empty(){
        evT.setText("Event:");
        descT.setText("Description:");
        dTe.setText("Date:");
        BeginT.setText("Begin:");
        EndT.setText("End:");
        costT.setText("Cost:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Title");
        model.addColumn("Description");
        model.addColumn("Date");
        model.addColumn("Beginning");
        model.addColumn("Ending");
        model.addColumn("Fee");
        eventTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        evT = new javax.swing.JLabel();
        descT = new javax.swing.JLabel();
        dTe = new javax.swing.JLabel();
        BeginT = new javax.swing.JLabel();
        EndT = new javax.swing.JLabel();
        costT = new javax.swing.JLabel();
        txtSearch2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        eventTable.setModel(model);
        /*
        eventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Title", "Decription", "Date", "Begin", "End", "Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        */
        eventTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eventTable);

        evT.setText("Event:");

        descT.setText("Description:");

        dTe.setText("Date:");

        BeginT.setText("begin:");

        EndT.setText("End':");

        costT.setText("Cost:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evT)
                    .addComponent(descT)
                    .addComponent(dTe)
                    .addComponent(BeginT)
                    .addComponent(EndT)
                    .addComponent(costT))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(evT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dTe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BeginT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EndT)
                .addGap(18, 18, 18)
                .addComponent(costT)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        txtSearch2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtSearch2.setText("Events");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtSearch2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eventTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventTableMouseClicked
        int row = eventTable.getSelectedRow();
        System.out.println("select event row"+eventTable.getModel().getValueAt(row, 4));
        if (row >= 0){
           BeginT.setText("Start at "+eventTable.getModel().getValueAt(row, 4));
           EndT.setText("End at "+eventTable.getModel().getValueAt(row, 5));
           costT.setText("Cost to participate "+eventTable.getModel().getValueAt(row, 6));
           dTe.setText("Event the "+eventTable.getModel().getValueAt(row, 3));
           descT.setText("Description "+eventTable.getModel().getValueAt(row, 2));
           evT.setText("Event: "+eventTable.getModel().getValueAt(row, 1));
       }else{
           empty();
       }
    }//GEN-LAST:event_eventTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BeginT;
    private javax.swing.JLabel EndT;
    private javax.swing.JLabel costT;
    private javax.swing.JLabel dTe;
    private javax.swing.JLabel descT;
    private javax.swing.JLabel evT;
    private javax.swing.JTable eventTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtSearch2;
    // End of variables declaration//GEN-END:variables
}
