/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.receptionGUI;

import HSMcontrollers.roomController;
import HSMmodel.RoomType;
import HSMmodel.room;
import dbConnexion.SQLiteJDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noria Soumbou
 */
public class RoomPanel extends javax.swing.JPanel {
    
    final private SQLiteJDBConnection db = new SQLiteJDBConnection();
    /**
     * Creates new form RoomPanel
     */
    public RoomPanel() {
        initComponents();
    }
    
     private void fillTable(){
        RoomType rmTpe =  new RoomType();
        room rm = new room();
        DefaultTableModel model = (DefaultTableModel) roomTable.getModel();
        String locate, desc, type;
        int id, bed, price;

        String sql1 = "SELECT * FROM rooms";
        try (Connection conn = db.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql1)) {
            try (ResultSet rs = pstmt.executeQuery()) {
                if(rs.next()) {
                    rmTpe.setTypeID(rs.getInt("idRoomType"));
                    rmTpe.getRoomType();            
                    rm.setRoom(rs.getInt("idRoom"),rs.getString("description"),rs.getString("location"),rs.getInt("idRoomType"));
                    roomController rc = new roomController(rm);
                    
                  model.addRow(new Object[]{ rm.getroomID(), rmTpe.getType(), rm.getDescription(), 
                     rm.getLocation(),rmTpe.getBeds(),rmTpe.getprice(),rc.roomReservationStatus()});
                }
                rs.close();
            }catch(SQLException e){ System.out.println("all room: "+e.getMessage()); }            
            pstmt.close();
        } catch (SQLException e) {
            System.out.println("all room db"+e.getMessage());
        }
        roomTable.removeColumn(roomTable.getColumnModel().getColumn(0)); // hide id
        roomTable.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Type");
        model.addColumn("Description");
        model.addColumn("Location");
        model.addColumn("Bed");
        model.addColumn("Price/night");
        model.addColumn("Status");
        roomTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roomTable.setModel(model);
        /*
        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        */
        jScrollPane1.setViewportView(roomTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roomTable;
    // End of variables declaration//GEN-END:variables
}
