/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.receptionGUI;

import HSMcontrollers.clientController;
import HSMcontrollers.roomController;
import dbConnexion.SQLiteJDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noria Soumbou
 */
public class TransportPanel extends javax.swing.JPanel {
    final private SQLiteJDBConnection db = new SQLiteJDBConnection();

    /**
     * Creates new form TransportPanel
     */
    public TransportPanel() {
        initComponents();
        
        ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor();
        ses.scheduleAtFixedRate(() -> {
            fillTable(); //food
        }, 0, 1, TimeUnit.MINUTES);
    }
    
    private void fillTable(){
        DefaultTableModel model = (DefaultTableModel)tableTransportation.getModel();
        clientController cc = new clientController();
        roomController rc = new roomController();

        String sql = "SELECT * FROM transportation";
        try (Connection conn = db.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            try (ResultSet rs = pstmt.executeQuery()) {
                while(rs.next()) {
                    cc.getClientById(rs.getInt("idClient"));
                    rc.getRoomById(rs.getInt("idRoom"));
                    String client = cc.fullName()+" in room"+ rc.getRoomLocation();;
                    model.addRow(new Object[]{ rs.getInt("idTrans"), "Taxi",client, rs.getDate("date").toString(),rs.getString("time"),
                        rs.getString("details"),rs.getString("status")});
                }
                rs.close();
            }catch(SQLException e){ System.out.println("all event: "+e.getMessage()); }            
            pstmt.close();
            //conn.close();
        } catch (SQLException e) {
            System.out.println("all event db"+e.getMessage());
        }
        //System.out.println(eventTable.getValueAt(1, 1));
        tableTransportation.removeColumn(tableTransportation.getColumnModel().getColumn(0)); // hide id
        tableTransportation.setDefaultEditor(Object.class, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        txtSearch2 = new javax.swing.JLabel();
        txtFirstName2 = new javax.swing.JLabel();
        fieldFirstName2 = new javax.swing.JTextField();
        buttonSearch2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Type transport");
        model.addColumn("Client");
        model.addColumn("Date");
        model.addColumn("Time");
        model.addColumn("Details");
        model.addColumn("Status");
        tableTransportation = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtSearch2.setText("Transport request");

        txtFirstName2.setText("Client:");

        fieldFirstName2.setEditable(false);

        buttonSearch2.setText("Requested");

        tableTransportation.setModel(model);

        /*
        tableTransportation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Type of Transportation", "Date Booked", "Paid Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        */
        jScrollPane5.setViewportView(tableTransportation);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch2)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(txtFirstName2)
                        .addGap(18, 18, 18)
                        .addComponent(fieldFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearch2))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch2)
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName2)
                    .addComponent(fieldFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch2))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSearch2;
    private javax.swing.JTextField fieldFirstName2;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tableTransportation;
    private javax.swing.JLabel txtFirstName2;
    private javax.swing.JLabel txtSearch2;
    // End of variables declaration//GEN-END:variables
}
