
package hotelGUI.clientGUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Noria Soumbou
 */
public class TransportPanel extends javax.swing.JPanel {
    
    GridBagLayout layout = new GridBagLayout();
    final TaxiFormPanel taxiView; 
    final RentalPanel  rentalView;
    final PublicTransPanel  publicView;

    /**
     * Creates new form TransportPanel
     */
    public TransportPanel(int cid, int rid) {
        initComponents();
        taxiView =  new TaxiFormPanel(cid,rid);
        rentalView = new RentalPanel();
        publicView = new PublicTransPanel();
        contentPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0; c.gridy = 0;        
       contentPanel.add(rentalView,c);
        rentalView.setVisible(false);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(taxiView,c);
       taxiView.setVisible(true);
        
        c.gridx = 0; c.gridy = 0;        
        contentPanel.add(publicView,c);
        publicView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        trainButton = new javax.swing.JButton();
        taxiButton = new javax.swing.JButton();
        rentalButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        trainButton.setBackground(new java.awt.Color(23, 63, 86));
        trainButton.setForeground(new java.awt.Color(255, 255, 255));
        trainButton.setText("Public transportation");
        trainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainButtonActionPerformed(evt);
            }
        });

        taxiButton.setBackground(new java.awt.Color(23, 63, 86));
        taxiButton.setForeground(new java.awt.Color(255, 255, 255));
        taxiButton.setText("Taxi");
        taxiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxiButtonActionPerformed(evt);
            }
        });

        rentalButton.setBackground(new java.awt.Color(23, 63, 86));
        rentalButton.setForeground(new java.awt.Color(255, 255, 255));
        rentalButton.setText("Rent a car");
        rentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(trainButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taxiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainButton)
                    .addComponent(taxiButton)
                    .addComponent(rentalButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainButtonActionPerformed
        publicView.setVisible(true);
        rentalView.setVisible(false);
        taxiView.setVisible(false);
        
    }//GEN-LAST:event_trainButtonActionPerformed

    private void taxiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxiButtonActionPerformed
        taxiView.setVisible(true);
        rentalView.setVisible(false);
        publicView.setVisible(false);
    }//GEN-LAST:event_taxiButtonActionPerformed

    private void rentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalButtonActionPerformed
        rentalView.setVisible(true);
        publicView.setVisible(false);
        taxiView.setVisible(false);
    }//GEN-LAST:event_rentalButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton rentalButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton taxiButton;
    private javax.swing.JButton trainButton;
    // End of variables declaration//GEN-END:variables
}
