/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.employeeGUI;

import HSMmodel.cleanup;
import dbConnexion.SQLiteJDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noria Soumbou, Jermaine Anderson
 */
public class cleaningDutiesPanel extends javax.swing.JPanel {
    
    final private SQLiteJDBConnection db = new SQLiteJDBConnection();

    /**
     * Creates new form cleaningDutiesPanel
     */
    public cleaningDutiesPanel() {
        initComponents();
        show_cleanup();
        
    }
    
    //Grab data from database
    public ArrayList<cleanup> cleanUpList(){
        ArrayList<cleanup> cleanUpList = new ArrayList<cleanup>();
        
        String sql = "SELECT * FROM maintenance";
            Connection conn = db.connect();
                    try {
                        Statement stmt = conn.createStatement();
                        ResultSet rs = stmt.executeQuery(sql);
                        cleanup cleanup;
                            while (rs.next()) {
                                    if(rs.getString("status").equalsIgnoreCase("Clean")|rs.getString("status").equalsIgnoreCase("Not Clean")){
                                cleanup = new cleanup(rs.getInt("idRoom"),rs.getString("status"));
                                cleanUpList.add(cleanup);
                                    }
                            }
                    } catch (SQLException e ) {
                        System.out.println(e.getMessage()); 
                      } 

        return cleanUpList;
    }

    //Show Data in JTable
    public void show_cleanup(){
        ArrayList<cleanup> list = cleanUpList();
        DefaultTableModel model = (DefaultTableModel)dutiesTable.getModel();
        Object [] row = new Object[2];

            for(int i =0; i<list.size(); i++){
                row [0] = list.get(i).getRoomNumber();
                row [1] = list.get(i).getStatus();
                
                model.addRow(row);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        txtChangeStatus = new javax.swing.JLabel();
        buttonCleaned = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dutiesTable = new javax.swing.JTable();

        txtChangeStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtChangeStatus.setText("Change Status:");

        buttonCleaned.setText("Cleaned");
        buttonCleaned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCleanedActionPerformed(evt);
            }
        });

        dutiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dutiesTable);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtChangeStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCleaned)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeStatus)
                    .addComponent(buttonCleaned))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1299, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCleanedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCleanedActionPerformed
        DefaultTableModel model = (DefaultTableModel)dutiesTable.getModel();
        int viewIndex = dutiesTable.getSelectedRow();
        int roomnumbervalue = (int )dutiesTable.getModel().getValueAt(viewIndex, 0);
        String statusvalue = "Clean";

        
         String sql1 = "UPDATE maintenance SET status = ?"+" WHERE idRoom= ?";

        try (Connection conn = db.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql1)){
            System.out.println(statusvalue);
            pstmt.setString(1, statusvalue);
            pstmt.setInt(2, roomnumbervalue);
            pstmt.executeUpdate();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            }

        //Resfresh
        model.setRowCount(0);
        show_cleanup();
    }//GEN-LAST:event_buttonCleanedActionPerformed
   
    
 
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCleaned;
    private javax.swing.JTable dutiesTable;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtChangeStatus;
    // End of variables declaration//GEN-END:variables
}
