/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.employeeGUI;

/**
 *
 * @author Noria Soumbou
 */
public class ClockPanel extends javax.swing.JPanel {

    /**
     * Creates new form clock
     */
    public ClockPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldClockIn = new javax.swing.JTextField();
        txtClockIn = new javax.swing.JLabel();
        buttonClockIn = new javax.swing.JButton();
        txtBreakS = new javax.swing.JLabel();
        fieldBreakStart = new javax.swing.JTextField();
        buttonSBreak = new javax.swing.JButton();
        txtBreakE = new javax.swing.JLabel();
        fieldTime = new javax.swing.JTextField();
        buttonEBreak = new javax.swing.JButton();
        txtClockOut = new javax.swing.JLabel();
        fieldClockOut = new javax.swing.JTextField();
        buttonClockOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldBreakEnd1 = new javax.swing.JTextField();

        fieldClockIn.setEditable(false);
        fieldClockIn.setFocusable(false);

        txtClockIn.setText("Clock-In Time");

        buttonClockIn.setText("Clock-In");

        txtBreakS.setText("Break Started ");

        fieldBreakStart.setEditable(false);
        fieldBreakStart.setFocusable(false);

        buttonSBreak.setText("Start Break");

        txtBreakE.setText("Break Ended");

        fieldTime.setEditable(false);
        fieldTime.setFocusable(false);

        buttonEBreak.setText("End Break");

        txtClockOut.setText("Clock-Out Time");

        fieldClockOut.setEditable(false);
        fieldClockOut.setFocusable(false);

        buttonClockOut.setText("Clock-Out");
        buttonClockOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClockOutMouseClicked(evt);
            }
        });

        jLabel1.setText("Date and time:");

        fieldBreakEnd1.setEditable(false);
        fieldBreakEnd1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtClockIn)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtClockOut)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldClockIn, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(fieldClockOut)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonClockIn)
                                .addGap(6, 6, 6)
                                .addComponent(buttonClockOut)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBreakS)
                                    .addComponent(txtBreakE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldBreakStart, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(fieldBreakEnd1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(buttonSBreak)
                                .addGap(115, 115, 115)
                                .addComponent(buttonEBreak))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(fieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClockIn)
                    .addComponent(buttonSBreak)
                    .addComponent(buttonEBreak)
                    .addComponent(buttonClockOut))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClockIn)
                    .addComponent(fieldClockIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBreakS)
                    .addComponent(fieldBreakStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBreakE)
                    .addComponent(fieldClockOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClockOut)
                    .addComponent(fieldBreakEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClockOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClockOutMouseClicked
        // TODO add your handling code here: clock out employee
    }//GEN-LAST:event_buttonClockOutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClockIn;
    private javax.swing.JButton buttonClockOut;
    private javax.swing.JButton buttonEBreak;
    private javax.swing.JButton buttonSBreak;
    private javax.swing.JTextField fieldBreakEnd1;
    private javax.swing.JTextField fieldBreakStart;
    private javax.swing.JTextField fieldClockIn;
    private javax.swing.JTextField fieldClockOut;
    private javax.swing.JTextField fieldTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtBreakE;
    private javax.swing.JLabel txtBreakS;
    private javax.swing.JLabel txtClockIn;
    private javax.swing.JLabel txtClockOut;
    // End of variables declaration//GEN-END:variables
}
