/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.employeeGUI;

import HSMmodel.delivery;
import dbConnexion.SQLiteJDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noria Soumbou, jermaine anderson
 */
public class deliveriesDutiesPanel extends javax.swing.JPanel {
    
    final private SQLiteJDBConnection db = new SQLiteJDBConnection();

    /**
     * Creates new form deliveriesDutiesPanel
     */
    public deliveriesDutiesPanel() {
        initComponents();

    }
    
//Grab data from database
    public ArrayList<delivery> deliveryList(){
        ArrayList<delivery> deliveryList = new ArrayList<delivery>();
        
        String sql = "SELECT * FROM delivery";
            Connection conn = db.connect();
                    try {
                        Statement stmt = conn.createStatement();
                        ResultSet rs = stmt.executeQuery(sql);
                        delivery delivery;
                            while (rs.next()) {
                                if(rs.getString("status").equalsIgnoreCase("Delivered")|rs.getString("status").equalsIgnoreCase("Not Delivered")){
                                delivery = new delivery(rs.getInt("idRoom"),rs.getString("type_delivery"),rs.getString("desc_delivery"),rs.getString("status"));
                                deliveryList.add(delivery);
                                }
                            }
                    } catch (SQLException e ) {
                        System.out.println(e.getMessage()); 
                      } 

        return deliveryList;
    }
    
    //Show Data in JTable
    public void show_delivery(){
        ArrayList<delivery> list = deliveryList();
        DefaultTableModel model = (DefaultTableModel)tableDuties_delivery.getModel();
        Object [] row = new Object[4];

            for(int i =0; i<list.size(); i++){
                row [0] = list.get(i).getRoomNumber();
                row [1] = list.get(i).getDes();
                row [2] = list.get(i).getDes1();
                row [3] = list.get(i).getStatus();
                
                model.addRow(row);
            }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableDuties_delivery = new javax.swing.JTable();
        txtChangeStatus = new javax.swing.JLabel();
        buttonDelivered = new javax.swing.JButton();

        tableDuties_delivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Meal ", "Allergies", "Delivery Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tableDuties_delivery);

        txtChangeStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtChangeStatus.setText("Change Status:");

        buttonDelivered.setText("Delivered");
        buttonDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeliveredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChangeStatus)
                            .addComponent(buttonDelivered))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtChangeStatus)
                .addGap(18, 18, 18)
                .addComponent(buttonDelivered)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1295, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeliveredActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableDuties_delivery.getModel();
        int viewIndex = tableDuties_delivery.getSelectedRow();
        int roomnumbervalue = (int )tableDuties_delivery.getModel().getValueAt(viewIndex, 0);
        String statusvalue = "Delivered";

        
         String sql1 = "UPDATE delivery SET status = ?"+" WHERE idRoom= ?";

        try (Connection conn = db.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql1)){
            pstmt.setString(1, statusvalue);
            pstmt.setInt(2, roomnumbervalue);
            pstmt.executeUpdate();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            }

        //Resfresh
        model.setRowCount(0);
        show_delivery();   
    
    }//GEN-LAST:event_buttonDeliveredActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelivered;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tableDuties_delivery;
    private javax.swing.JLabel txtChangeStatus;
    // End of variables declaration//GEN-END:variables
}
