/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelGUI.employeeGUI;

import hotelGUI.welcomePage;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Noria Soumbou
 */
public class EmployeePage extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    final ClockPanel clockView;
    final ProfilePanel profileView;
    final HoursPanel hoursView;
    final DutiesPanel dutiesView;

    /**
     * Creates new form EmployeeGUI
     */
    public EmployeePage() {
        initComponents();
        clockView = new ClockPanel();
        profileView = new ProfilePanel();
        hoursView = new HoursPanel();
        dutiesView = new DutiesPanel();

        contentPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();

        c.gridx = 0;
        c.gridy = 0;
        contentPanel.add(profileView, c);
        this.pack();
        profileView.setVisible(false);

        c.gridx = 0;
        c.gridy = 0;
        contentPanel.add(clockView, c);
        this.pack();
        clockView.setVisible(false);

        c.gridx = 0;
        c.gridy = 0;
        contentPanel.add(hoursView, c);
        this.pack();
        hoursView.setVisible(false);

        c.gridx = 0;
        c.gridy = 0;
        contentPanel.add(dutiesView, c);
        this.pack();
        dutiesView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        profileMenu = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        clockMenu = new javax.swing.JMenuItem();
        hoursMenu = new javax.swing.JMenuItem();
        dutiesMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Main Terminal");
        setResizable(false);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        jMenu1.setText("User");

        profileMenu.setText("Profile");
        profileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuActionPerformed(evt);
            }
        });
        jMenu1.add(profileMenu);

        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Go To");

        clockMenu.setText("Clock In / Out");
        clockMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockMenuActionPerformed(evt);
            }
        });
        jMenu2.add(clockMenu);

        hoursMenu.setText("Hours");
        hoursMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursMenuActionPerformed(evt);
            }
        });
        jMenu2.add(hoursMenu);

        dutiesMenu.setText("Duties");
        dutiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dutiesMenuActionPerformed(evt);
            }
        });
        jMenu2.add(dutiesMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileMenuActionPerformed
        // TODO add your handling code here:
        profileView.setVisible(true);
        hoursView.setVisible(false);
        clockView.setVisible(false);
        dutiesView.setVisible(false);
    }//GEN-LAST:event_profileMenuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here: logout user
        this.dispose();
        new welcomePage().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void clockMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockMenuActionPerformed
        // TODO add your handling code here:
        profileView.setVisible(false);
        hoursView.setVisible(false);
        clockView.setVisible(true);
        dutiesView.setVisible(false);
    }//GEN-LAST:event_clockMenuActionPerformed

    private void hoursMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursMenuActionPerformed
        // TODO add your handling code here:
        profileView.setVisible(false);
        hoursView.setVisible(true);
        clockView.setVisible(false);
        dutiesView.setVisible(false);
    }//GEN-LAST:event_hoursMenuActionPerformed

    private void dutiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dutiesMenuActionPerformed
        profileView.setVisible(false);
        hoursView.setVisible(false);
        clockView.setVisible(false);
        dutiesView.setVisible(true);
    }//GEN-LAST:event_dutiesMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clockMenu;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuItem dutiesMenu;
    private javax.swing.JMenuItem hoursMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem profileMenu;
    // End of variables declaration//GEN-END:variables
}
